DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
   id   INT NOT NULL AUTO_INCREMENT,
   GENRE_NAME VARCHAR(255) NOT NULL,
   PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
   id   INT NOT NULL AUTO_INCREMENT,
   FIRST_NAME VARCHAR(255) NOT NULL,
   SECOND_NAME VARCHAR(255) NOT NULL,
   BIRTHDAY DATE NOT NULL,
   PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
   id   INT NOT NULL AUTO_INCREMENT,
   TITLE VARCHAR(255) NOT NULL,
   AUTHOR_ID INT NOT NULL,
   GENRE_ID INT NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (AUTHOR_ID)  REFERENCES AUTHORS (Id),
   FOREIGN KEY (GENRE_ID)  REFERENCES GENRES (Id)
);

DROP TABLE IF EXISTS REVIEWS;
CREATE TABLE REVIEWS(
   ID INT NOT NULL AUTO_INCREMENT,
   BOOK_ID INT NOT NULL,
   TEXT VARCHAR(255) NOT NULL,
   REVIEWER VARCHAR(255) NOT NULL,
   CREATION_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (Id) ON DELETE CASCADE,
   PRIMARY KEY (ID)
);