DROP TABLE IF EXISTS spring.GENRES;
CREATE TABLE spring.GENRES(
   id   INT NOT NULL AUTO_INCREMENT,
   GENRE_NAME VARCHAR(255) NOT NULL,
   PRIMARY KEY (ID),
   UNIQUE KEY `GENRE_NAME_UNIQUE` (`GENRE_NAME` ASC) VISIBLE
);

DROP TABLE IF EXISTS spring.AUTHORS;
CREATE TABLE spring.AUTHORS(
   id   INT NOT NULL AUTO_INCREMENT,
   FIRST_NAME VARCHAR(255) NOT NULL,
   SECOND_NAME VARCHAR(255) NOT NULL,
   BIRTHDAY DATE NOT NULL,
   PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS spring.BOOKS;
CREATE TABLE spring.BOOKS(
   id   INT NOT NULL AUTO_INCREMENT,
   TITLE VARCHAR(255) NOT NULL,
   AUTHOR_ID INT NOT NULL,
   GENRE_ID INT NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (AUTHOR_ID)  REFERENCES AUTHORS (Id),
   FOREIGN KEY (GENRE_ID)  REFERENCES GENRES (Id)
);